[package]
name = "taarable"
version = "0.1.0-alpha"
description = "UART communication interface for the TAAR-x robotic arms"
authors = ["Hydle Research Group"]
edition = "2024"
license = "GPL-3.0"
repository = "https://github.com/Hydle-Research-Group/taarable"
publish = false

[dependencies]
serialport = "4.9.0"
slint = { version = "1.16.1", features = ["live-preview"] }

[build-dependencies]
slint-build = "1.16.1"
