import {
    VerticalBox,
    HorizontalBox,
    TextEdit,
    Button,
    ComboBox,
    LineEdit,
} from "std-widgets.slint";

export component AppWindow inherits Window {
    in property <[string]> ports;
    in-out property <string> command;
    in-out property <string> active_port: ports[0];
    in-out property <string> interface;
    // disable toggle (re-enabled when command finished)
    in-out property <bool> enable_command_sending: true;
    callback command_sent();
    callback port_changed();

    HorizontalBox {
        VerticalBox {
            Rectangle {
                width: 260px;
                height: 260px;
                border-radius: self.width / 2;
                background: #202020;

                Button {
                    x: parent.width / 2 - self.width / 2;
                    y: 20px;
                    enabled: enable_command_sending;
                    text: "+arm";

                    clicked => {
                        command = "arm+";
                        command_sent();
                    }
                }

                Button {
                    x: 20px;
                    y: parent.height / 2 - self.height / 2;
                    enabled: enable_command_sending;
                    text: "+base";

                    clicked => {
                        command = "base+";
                        command_sent();
                    }
                }

                Button {
                    x: parent.width / 2 - self.width / 2;
                    y: parent.height / 2 - self.height / 2;
                    enabled: enable_command_sending;
                    text: "home";

                    clicked => {
                        command = "home";
                        command_sent();
                    }
                }

                Button {
                    x: parent.width - self.width - 20px;
                    y: parent.height / 2 - self.height / 2;
                    enabled: enable_command_sending;
                    text: "-base";

                    clicked => {
                        command = "base-";
                        command_sent();
                    }
                }

                Button {
                    x: parent.width / 2 - self.width / 2;
                    y: parent.height - self.height - 20px;
                    enabled: enable_command_sending;
                    text: "-arm";

                    clicked => {
                        command = "arm-";
                        command_sent();
                    }
                }
            }

            Rectangle {
                horizontal-stretch: 1;
            }

            VerticalBox {
                HorizontalBox {
                    Text {
                        text: "x:";
                    }

                    x := LineEdit {
                        input-type: decimal;
                        text: "0.0";
                    }

                    Text {
                        text: "y:";
                    }

                    y := LineEdit {
                        input-type: decimal;
                        text: "0.0";
                    }

                    Text {
                        text: "z:";
                    }

                    z := LineEdit {
                        input-type: decimal;
                        text: "0.0";
                    }
                }

                Button {
                    text: "Move To Position";
                    clicked => {
                        command = "moveto " + x.text + " " + y.text + " " + z.text;
                        command_sent();
                    }
                }
            }
        }

        VerticalBox {
            HorizontalBox {
                Rectangle {
                    horizontal-stretch: 1;
                }

                Button {
                    text: "Clear Messages";
                    clicked => {
                        interface = "";
                    }
                }

                ComboBox {
                    model: ports;
                    selected => {
                        active_port = ports[self.current-index];
                        port_changed();
                    }
                }
            }

            TextEdit {
                placeholder-text: "Commands will be seen here";
                read-only: true;
                text: interface;
            }

            HorizontalBox {
                command_input := LineEdit {
                    enabled: enable_command_sending;
                    accepted => {
                        command = command_input.text;
                        command_input.text = "";
                        command_sent();
                    }
                }

                send_button := Button {
                    width: 15%;
                    text: "Send";
                    enabled: enable_command_sending;
                    clicked => {
                        command = command_input.text;
                        command_input.text = "";
                        command_sent();
                    }
                }
            }
        }
    }
}
