import {
    VerticalBox,
    HorizontalBox,
    TextEdit,
    Button,
    ComboBox,
    LineEdit,
} from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "TAARABLE";
    icon: @image-url("../assets/icon.svg");

    in property <[string]> ports;
    in-out property <string> command;
    in-out property <string> active_port: ports[0];
    in-out property <string> interface;
    // disable toggle (re-enabled when command finished)
    in-out property <bool> enable_command_sending: true;
    callback command_sent();
    callback port_changed();

    VerticalBox {
        ComboBox {
            model: ports;
            selected => {
                active_port = ports[self.current-index];
                port_changed();
            }
        }

        HorizontalBox {
            VerticalBox {
                Rectangle {
                    width: 260px;
                    height: 260px;
                    drop-shadow-color: #0f0f0f;
                    drop-shadow-blur: 10px;
                    border-color: #0f0f0f;
                    border-width: 1px;
                    border-radius: self.width / 2;
                    background: #202020;

                    Button {
                        x: parent.width / 2 - self.width / 2;
                        y: 20px;
                        enabled: enable_command_sending;
                        text: "+arm";

                        clicked => {
                            command = "arm+";
                            command_sent();
                        }
                    }

                    Button {
                        x: 20px;
                        y: parent.height / 2 - self.height / 2;
                        enabled: enable_command_sending;
                        text: "+base";

                        clicked => {
                            command = "base+";
                            command_sent();
                        }
                    }

                    Button {
                        x: parent.width / 2 - self.width / 2;
                        y: parent.height / 2 - self.height / 2;
                        enabled: enable_command_sending;
                        text: "home";

                        clicked => {
                            command = "home";
                            command_sent();
                        }
                    }

                    Button {
                        x: parent.width - self.width - 20px;
                        y: parent.height / 2 - self.height / 2;
                        enabled: enable_command_sending;
                        text: "-base";

                        clicked => {
                            command = "base-";
                            command_sent();
                        }
                    }

                    Button {
                        x: parent.width / 2 - self.width / 2;
                        y: parent.height - self.height - 20px;
                        enabled: enable_command_sending;
                        text: "-arm";

                        clicked => {
                            command = "arm-";
                            command_sent();
                        }
                    }
                }
            }

            VerticalBox {
                TextEdit {
                    placeholder-text: "Messages will be seen here";
                    read-only: true;
                    text: interface;
                }
            }
        }

        Rectangle {
            vertical-stretch: 1;
        }

        HorizontalBox {
            Text {
                text: "x:";
            }

            x := LineEdit {
                input-type: decimal;
                text: "0.0";
            }

            Text {
                text: "y:";
            }

            y := LineEdit {
                input-type: decimal;
                text: "0.0";
            }

            Text {
                text: "z:";
            }

            z := LineEdit {
                input-type: decimal;
                text: "0.0";
            }

            Button {
                text: "Move To Position";
                clicked => {
                    command = "moveto " + x.text + " " + y.text + " " + z.text;
                    command_sent();
                }
            }
        }

        HorizontalBox {
            command_input := LineEdit {
                enabled: enable_command_sending;
                placeholder-text: "Enter a command";
                accepted => {
                    command = command_input.text;
                    command_input.text = "";
                    command_sent();
                }
            }

            send_button := Button {
                width: 15%;
                text: "Send";
                enabled: enable_command_sending;
                clicked => {
                    command = command_input.text;
                    command_input.text = "";
                    command_sent();
                }
            }

            Button {
                text: "Clear";
                clicked => {
                    interface = "";
                }
            }
        }
    }
}
